### PR TITLE
TSCH: fix channel_offset in the logs if taken from a packet, and refactor TSCH channel / channel_offset selection inside a slot

### LINKED ISSUE #1181: TSCH log does not print the right channel offset
PR #1053 introduced multiple channel option for unicast slotframe. 
tsch-log still prints channel offset from the link not the actual channel offset.

### PR DESCRIPTION
**Pull request by atiselsts**
Fixes #1181

### CODE REVIEW

**Comment by atiselsts** [comment]
Failures in the BR tests look unrelated.

File: os/net/mac/tsch/tsch-slot-operation.h [hunk 1]
```diff
@@ -67,11 +67,10 @@ extern int tsch_current_burst_count;
  * The offset to the ASN and performs a hopping sequence lookup.
  *
  * \param asn A given ASN
- * \param channel_offset Link's channel offset
- * \param p Packet that can override the link's channel offset
+ * \param channel_offset Given channel offset
  * \return The resulting channel
  */
-uint8_t tsch_calculate_channel(struct tsch_asn_t *asn, uint16_t channel_offset, struct tsch_packet *p);
+uint8_t tsch_calculate_channel(struct tsch_asn_t *asn, uint16_t channel_offset);
```
Comment (simonduq) [inline os/net/mac/tsch/tsch-slot-operation.h:73]: Looks like this can be made now static

Comment (atiselsts) [reply os/net/mac/tsch/tsch-slot-operation.h]: True - it makes sense to keep it in the .c file. I updated the PR.
